# Generated by Django 4.0 on 2021-12-30 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_alter_auctions_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctions',
            name='ImageURL',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
