# Generated by Django 3.2.9 on 2021-12-27 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ImageURL', models.URLField(blank=True)),
                ('Title', models.CharField(max_length=64)),
                ('Description', models.CharField(max_length=50)),
            ],
        ),
    ]
