# Generated by Django 3.2.9 on 2021-12-27 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0002_wishlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlist',
            name='cart',
            field=models.BooleanField(default=False),
        ),
    ]
