# Generated by Django 3.2.9 on 2021-12-28 09:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0004_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='Items',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Items', to='first.products'),
        ),
    ]
