# Generated by Django 3.2.9 on 2021-12-30 09:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0007_alter_products_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='Image',
            field=models.TextField(validators=[django.core.validators.URLValidator()]),
        ),
        migrations.RemoveField(
            model_name='wishlist',
            name='item',
        ),
        migrations.AddField(
            model_name='wishlist',
            name='item',
            field=models.ManyToManyField(blank=True, related_name='item', to='first.Products'),
        ),
    ]
