# Generated by Django 4.0 on 2021-12-30 10:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0008_auto_20211230_1526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='Image',
            field=models.URLField(validators=[django.core.validators.URLValidator()]),
        ),
    ]
