# Generated by Django 3.2.9 on 2021-12-31 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0010_alter_products_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='price',
            field=models.IntegerField(default=None),
        ),
    ]
