# Generated by Django 3.2.9 on 2022-01-01 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0011_products_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, max_length=200)),
            ],
        ),
    ]
